name: asr
dependencies:
- python=2.7.14
- matplotlib=1.5.3
- pandas=0.18.1
- numpy=1.11
- scipy=0.19.1
- jupyter
- mkl-service
- theano=1.0.1
- scikit-learn
- pip:
  - tqdm==4.19.2
  - seaborn==0.7.1
  - opencv_python==3.1.0.3
  - git+https://github.com/Lasagne/Lasagne.git
  - madmom==0.15.1
  - omr==0.0.73
  - PyYAML==3.12
  - scikit-image
  - music21
  - muscima==0.10.0
  - dtw==1.3