name: asr

dependencies:
- python=3.6
- matplotlib=3.0.2
- pandas=0.24.1
- numpy=1.15
- scipy=1.1.0
- jupyter=1.0.0
- mkl-service=1.1.2
- theano=1.0.3
- pygpu=0.7.6
- scikit-learn=0.20.2
- cython=0.29.6

- pip:
  - tqdm==4.31.1
  - seaborn==0.7.1
  - opencv_python==3.1.0.4
  - git+https://github.com/Lasagne/Lasagne.git
  - git+https://github.com/CPJKU/madmom.git@v0.16.1
  - omr==0.0.73
  - PyYAML==3.13
  - scikit-image==0.14.2
  - git+git://github.com/hajicj/muscima#egg=muscima
  - dtw==1.3.3
