name: asr
dependencies:
- backports=1.0=py27_1
- backports.shutil_get_terminal_size=1.0.0=py_3
- backports_abc=0.5=py27_0
- bleach=1.5.0=py27_0
- bzip2=1.0.6=3
- ca-certificates=2017.11.5=0
- certifi=2016.2.28=py27_0
- clyent=1.2.2=py27_0
- cmake=3.10.0=4
- configparser=3.5.0=py27_0
- curl=7.55.1=0
- dbus=1.10.20=0
- decorator=4.1.2=py27_0
- entrypoints=0.2.3=py27_0
- enum34=1.1.6=py27_0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.7=2
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- html5lib=0.9999999=py27_0
- icu=56.1=4
- ipykernel=4.6.1=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- ipywidgets=6.0.0=py27_0
- jinja2=2.9.6=py27_0
- jpeg=9b=0
- jsonschema=2.6.0=py27_0
- jupyter_client=5.2.2=py27_0
- jupyter_core=4.4.0=py_0
- krb5=1.14.2=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libgpuarray=0.7.5=0
- libiconv=1.14=0
- libpng=1.6.30=1
- libsodium=1.0.10=0
- libssh2=1.8.0=2
- libuv=1.11.0=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- mako=1.0.6=py27_0
- markupsafe=1.0=py27_0
- mistune=0.7.4=py27_0
- mkl=2017.0.3=0
- mkl-service=1.1.2=py27_3
- nbconvert=5.2.1=py27_0
- nbformat=4.4.0=py27_0
- ncurses=5.9=10
- nose=1.3.7=py27_1
- notebook=5.0.0=py27_0
- numpy=1.13.1=py27_0
- openssl=1.0.2l=0
- pandocfilters=1.4.2=py27_0
- path.py=10.3.1=py27_0
- pathlib2=2.3.0=py27_0
- pcre=8.39=1
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_1
- prompt_toolkit=1.0.15=py27_0
- ptyprocess=0.5.2=py27_0
- pygments=2.2.0=py27_0
- pygpu=0.7.5=py27_0
- pyqt=4.11.4=py27_4
- python=2.7.14=4
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- pyyaml=3.12=py27_0
- pyzmq=16.0.2=py27_0
- qt=4.8.6=3
- qtconsole=4.3.1=py27_0
- readline=7.0=0
- requests=2.14.2=py27_0
- rhash=1.3.4=0
- scandir=1.5=py27_0
- scipy=0.19.1=np113py27_0
- setuptools=36.4.0=py27_1
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.20.1=0
- ssl_match_hostname=3.5.0.1=py27_0
- terminado=0.6=py27_0
- testpath=0.3.1=py27_0
- theano=1.0.1=py27_1
- tk=8.6.6=0
- tornado=4.5.2=py27_0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- webencodings=0.5=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=3.0.2=py27_0
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.3=0
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.11=0
- pip:
  - abjad==2.21
  - backports-abc==0.5
  - backports.functools-lru-cache==1.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - backports.weakref==1.0.post1
  - cycler==0.10.0
  - cython==0.27.3
  - dtw==1.3
  - et-xmlfile==1.0.1
  - funcsigs==1.0.2
  - future==0.16.0
  - futures==3.2.0
  - ipython-genutils==0.2.0
  - jdcal==1.3
  - jupyter-client==5.1.0
  - jupyter-console==5.2.0
  - jupyter-core==4.3.0
  - lasagne==0.2.dev1
  - lxml==4.1.1
  - madmom==0.15.1
  - markdown==2.6.11
  - matplotlib==2.1.1
  - mido==1.2.8
  - mir-eval==0.4
  - mock==2.0.0
  - muscima==0.3.2.dev0
  - music21==4.1.0
  - networkx==2.0
  - opencv-python==3.1.0.3
  - openpyxl==2.4.9
  - pandas==0.18.1
  - pbr==3.1.1
  - pdfminer==20140328
  - pillow==5.0.0
  - ply==3.10
  - prompt-toolkit==1.0.15
  - protobuf==3.5.1
  - pyparsing==2.2.0
  - python-ly==0.9.5
  - python-midi==0.2.4
  - pywavelets==0.5.2
  - scikit-image==0.13.1
  - scikit-learn==0.19.1
  - seaborn==0.7.1
  - subprocess32==3.2.7
  - tensorboardx==1.0
  - tensorflow-gpu==1.4.1
  - tensorflow-tensorboard==0.4.0
  - tqdm==4.19.5
  - werkzeug==0.14.1