name: asr
dependencies:
- python=3.6
- matplotlib
- pandas
- numpy=1.12
- scipy
- jupyter
- mkl-service
- theano
- pygpu
- scikit-learn
- cython
- pip:
  - tqdm==4.19.2
  - seaborn==0.7.1
  - opencv_python==3.1.0.4
  - git+https://github.com/Lasagne/Lasagne.git
  - madmom==0.16.1
  - omr==0.0.73
  - PyYAML==3.12
  - scikit-image
  - muscima==0.10.0
  - dtw==1.3
  - git+https://github.com/cuthbertLab/music21.git@v4.1.0
